[workspace]
authors = ["avanscoyoc <amy.e.van.scoyoc@gmail.com>"]
channels = ["conda-forge"]
name = "pa_proj"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
ipython = ">=9.3.0,<10"
ipykernel = ">=6.29.5,<7"
pixi-kernel = ">=0.6.3,<0.7"
numpy = ">=2.3.0,<3"
pandas = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
earthengine-api = ">=1.5.21,<2"
geemap = ">=0.35.3,<0.36"
folium = ">=0.20.0,<0.21"
ipyleaflet = ">=0.20.0,<0.21"
geopandas = ">=1.1.0,<2"
gdal = ">=3.11.0,<4"
google-cloud-storage = ">=3.1.1,<4"
jupyterlab = ">=4.4.3,<5"
